webtalk_init -webtalk_dir C:/000mygit/myeie/001CourseWare/004IntegratedSystemDesign/Lab/lab1/ChanghongLi_lab1_183/ChanghongLi_lab1_183.sim/sim_1/behav/xsim/xsim.dir/lab1_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 29 18:15:27 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9fd6d7e6-2679-43a9-8414-41ecd5f68d9c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5820b1d2063e45e89b78c8c4893dcc3b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6560_KB" -context "xsim\\usage"
webtalk_transmit -clientid 389112728 -regid "" -xml C:/000mygit/myeie/001CourseWare/004IntegratedSystemDesign/Lab/lab1/ChanghongLi_lab1_183/ChanghongLi_lab1_183.sim/sim_1/behav/xsim/xsim.dir/lab1_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/000mygit/myeie/001CourseWare/004IntegratedSystemDesign/Lab/lab1/ChanghongLi_lab1_183/ChanghongLi_lab1_183.sim/sim_1/behav/xsim/xsim.dir/lab1_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/000mygit/myeie/001CourseWare/004IntegratedSystemDesign/Lab/lab1/ChanghongLi_lab1_183/ChanghongLi_lab1_183.sim/sim_1/behav/xsim/xsim.dir/lab1_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
