@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Dec 01 14:04:55 +0000 2023
=======
REM Generated by Vivado on Thu Nov 30 16:23:47 +0000 2023
>>>>>>> bb1f18b13b9b3882f3503c5f32f8a3be289884ef
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xvlog --incr --relax -prj div8_vlog.prj"
call xvlog  --incr --relax -prj div8_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -prj exam_tb_vlog.prj"
call xvlog  --incr --relax -prj exam_tb_vlog.prj -log xvlog.log
>>>>>>> bb1f18b13b9b3882f3503c5f32f8a3be289884ef
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
