@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Dec 01 14:04:56 +0000 2023
=======
REM Generated by Vivado on Thu Nov 30 16:23:49 +0000 2023
>>>>>>> bb1f18b13b9b3882f3503c5f32f8a3be289884ef
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xelab  -wto fc5d0c7a96a44841b0f93b3ff8ae4044 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot div8_behav xil_defaultlib.div8 xil_defaultlib.glbl -log elaborate.log
=======
call xelab  -wto fc5d0c7a96a44841b0f93b3ff8ae4044 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot exam_tb_behav xil_defaultlib.exam_tb xil_defaultlib.glbl -log elaborate.log
>>>>>>> bb1f18b13b9b3882f3503c5f32f8a3be289884ef
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
