@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 14 13:15:49 +0000 2023
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim lab2_top_tb_behav -key {Behavioral:sim_1:Functional:lab2_top_tb} -tclbatch lab2_top_tb.tcl -view C:/Users/lic9/Desktop/000mygit/myeie/001CourseWare/004IntegratedSystemDesign/Lab/lab2/002PRJ/ChanghongLi_lab2/lab2_top_tb_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
