@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Dec 05 21:22:48 +0000 2023
=======
<<<<<<< HEAD
REM Generated by Vivado on Fri Dec 01 14:04:57 +0000 2023
=======
REM Generated by Vivado on Thu Nov 30 16:23:52 +0000 2023
>>>>>>> bb1f18b13b9b3882f3503c5f32f8a3be289884ef
>>>>>>> 157fb42d2bca27c0cf08db73ec84f97db60c5813
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xsim div8_behav -key {Behavioral:sim_1:Functional:div8} -tclbatch div8.tcl -view C:/Users/lic9/Desktop/000mygit/myeie/001CourseWare/004IntegratedSystemDesign/Lab/lab2/002PRJ/ChanghongLi_lab2/lab2_top_tb_behav1.wcfg -log simulate.log
=======
call xsim exam_tb_behav -key {Behavioral:sim_1:Functional:exam_tb} -tclbatch exam_tb.tcl -view D:/000Mygit/myeie/001CourseWare/004IntegratedSystemDesign/Lab/lab2/002PRJ/ChanghongLi_lab2/lab2_top_tb_behav1.wcfg -log simulate.log
>>>>>>> bb1f18b13b9b3882f3503c5f32f8a3be289884ef
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
